name: Build Plasmo Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install -g pnpm

      - run: pnpm install

      - run: npm rebuild --verbose sharp

      - run: pnpm run build

      - run: |
          mkdir dist-zip
          cd build/chrome-mv3-prod
          zip -r ../../dist-zip/golfin-extension.zip ./*

      - name: Upload artefato
        uses: actions/upload-artifact@v4
        with:
            name: golfin-extension
            path: dist-zip/golfin-extension.zip
